package com.amitcodes.soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-28T15:09:03.895+05:30
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://www.amitcodes.com/", name = "HelloPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloPortType {

    @WebResult(name = "Greeting", targetNamespace = "http://www.amitcodes.com/", partName = "response")
    @WebMethod(action = "http://www.amitcodes.com/sayHello")
    public Greeting sayHello(
        @WebParam(partName = "personName", name = "nameArg", targetNamespace = "http://www.amitcodes.com/")
        java.lang.String personName
    );
}
