
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.amitcodes.soap.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-26T06:42:18.652+05:30
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloService",
                      portName = "HelloPort",
                      targetNamespace = "http://www.amitcodes.com/",
                      wsdlLocation = "file:/C:/cygwin64/home/meghamit/workspace/poc/soap_minimal_contract_first_ws/src/main/resources/wsdl/HelloWorld.wsdl",
                      endpointInterface = "com.amitcodes.soap.ws.HelloPortType")
                      
public class HelloPortTypeImpl implements HelloPortType {

    private static final Logger LOG = Logger.getLogger(HelloPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.amitcodes.soap.ws.HelloPortType#sayHello(java.lang.String  personName )*
     */
    public com.amitcodes.soap.ws.Greeting sayHello(java.lang.String personName) { 
        LOG.info("Executing operation sayHello");
        System.out.println(personName);
        try {
            com.amitcodes.soap.ws.Greeting _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
